apiVersion: v1
kind: Service
metadata:
  name: maria-db
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
      app: "{{ .Release.Name }}-maria"
