{{- if .Values.deno.ingress.enabled -}}
{{- $fullName := (.Values.deno.service.name | default .Release.Name) -}}
{{- $svcPort := .Values.deno.service.port -}}
{{- if and .Values.deno.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.deno.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.deno.ingress.annotations "kubernetes.io/ingress.class" .Values.deno.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oe.labels" . | nindent 4 }}
  {{- with .Values.deno.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.deno.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.deno.ingress.className }}
  {{- end }}
  {{- if .Values.deno.ingress.tls }}
  tls:
    {{- range .Values.deno.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.deno.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
