{{- if and .Values.deno.persistence.enabled (not .Values.deno.persistence.pv.existingStorage) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.deno.persistence.pv.name | default .Release.Name }}-ws"
  namespace: {{ .Release.Namespace }}
  labels:
   {{- include "oe.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.deno.persistence.pv.storage }}
  accessModes:
  {{- range .Values.mariadb.persistence.pv.accessModes }}
    - {{ . | quote }}
  {{- end }}
  hostPath:
    path: {{ .Values.deno.persistence.pv.hostPath }}
  persistentVolumeReclaimPolicy: {{ .Values.deno.persistence.pv.persistentVolumeReclaimPolicy }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ if .Values.deno.persistence.pvc.existingClaim }}{{ .Values.deno.persistence.pvc.existingClaim }}-ws{{ else  if .Values.deno.persistence.pvc.name }}{{ .Values.deno.persistence.pvc.name}}-ws{{ else }}{{ default .Release.Name }}-ws{{ end }}
{{- end }}