apiVersion: v1
kind: Secret
metadata:
  name: "{{ default .Release.Name }}-maria"
  namespace: {{ .Release.Namespace }}
data:
  hostname: {{ .Values.mariadb.service.name | default .Release.Name | b64enc | quote }}
  username: {{ "root" | b64enc | quote }}
  database: {{ .Values.mariadb.auth.database | b64enc | quote }}
  password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}