apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-maria"
  labels:
    app: "{{ .Release.Name }}-maria"
spec:
  {{- if not .Values.mariadb.autoscaling.enabled }}
  replicas: {{ .Values.mariadb.replicaCount }}
  {{- end }}
  serviceName: "maria-db"
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-maria"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-maria"
    spec:
      {{- with .Values.mariadb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: maria-db
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          ports:
          -  containerPort: 3306
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
          env:
          - name: MARIADB_ROOT_PASSWORD
            value: {{ .Values.mariadb.auth.rootPassword }}
          - name: MARIADB_DATABASE
            value: {{ .Values.mariadb.auth.database }}
      {{- if .Values.mariadb.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.mariadb.persistence.volumes.mountPath }}
              name: {{ .Values.mariadb.persistence.volumes.name | default .Release.Name }}
  volumeClaimTemplates:
  - metadata:
     name: {{ .Values.mariadb.persistence.volumes.name | default .Release.Name }}
    spec:
      storageClassName: ""
      accessModes:
        {{- range .Values.mariadb.persistence.pv.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.mariadb.persistence.pvc.storage }}
      {{- end }}
